### ISSUE TITLE
🎨 - Content List fragment (Media)

### ISSUE THREAD

**Issue by NateRickard** [technicalpoets/producer#16]
- Related to build task #15
- Make the ViewCells in the content/media list pretty

<img width="487" alt="screenshot 2017-08-21 17 38 18" src="https://user-images.githubusercontent.com/2753695/29539360-8b8ad81e-8697-11e7-9cf0-3e1b613e6002.png">

**Comment by hieunhums** [comment]
Icons needed: 
i_segment_andrew - tab
i_segment_saved - tab
i_tab_profile - menu item
i_tab_compose - menu item
i_tab_record
i_tab_saved
i_download


// incomplete, tbc
